---
ID: "81c2d465-66d5-48e5-bbe7-118699952040"
Parent: "3cb97b67-7d4c-4b01-99a9-daa147c9f307"
Template: "99f8905d-4a87-4eb8-9f8b-a9bebfb3add6"
Path: /sitecore/layout/Renderings/Feature/Product/ProductDetail
SharedFields:
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Project/RainflyTraining/ProductPage
- ID: "51b435bc-f7b9-478a-9c51-52916af96ff5"
  Hint: Path
  Value: /Views/Products/ProductDetail.cshtml
- ID: "7d24e54f-5c16-4314-90c9-6051aa1a7da1"
  Hint: Parameters Template
  Value: 
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: "query:./ancestor-or-self::*[@@templatename='Site']/Home/*[@@templateid='{9EC14A2D-55F8-4540-9137-E66F01B916D1}']"
- ID: "e441abe7-2ca3-4640-ae26-3789967925d7"
  Hint: Compatible Renderings
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220818T145735Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "582a4a07-3c41-46ad-a855-a41df979109a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220829T145625Z
