---
ID: "60850c45-fbb7-40ab-a11f-7fbf873e01d0"
Parent: "efce9b35-3cfa-4bda-853d-bf4614b3247f"
Template: "efce9b35-3cfa-4bda-853d-bf4614b3247f"
Path: /sitecore/templates/Feature/Product/Product/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220801T121752Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "25372bd3-bc63-40cd-a5fb-3efb8cd43b31"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220801T121752Z
