---
ID: "84de0d78-e1de-4c81-8754-63ec516235be"
Parent: "2bb5a4b6-4547-4a73-9528-41c5c26dfd24"
Template: "2bb5a4b6-4547-4a73-9528-41c5c26dfd24"
Path: /sitecore/templates/Foundation/Content/CSSClass/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220818T155557Z
    - ID: "260cfb47-f7ee-4f9c-a8db-ff98523cae49"
      Hint: Classname
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e18be8ee-81aa-44fe-bc1f-742dbaa32b8b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220818T155607Z
