---
ID: "ff6cfa1f-232b-4fcc-a035-e73baba215c2"
Parent: "f2201a7b-97be-4c11-b9be-e17eb1b10639"
Template: "239f9cf4-e5a0-44e0-b342-0f32cd4c6d8b"
Path: /sitecore/templates/Foundation/Content/Site
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221014T192117Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\scott.gillis@paragon-inc.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\scott.gillis@paragon-inc.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d20f38b5-e119-480d-959e-4c4f846efe7d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\scott.gillis@paragon-inc.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221014T192117Z
