---
ID: "d9082c40-ea8e-458b-95de-c4e86092f519"
Parent: "583d498c-b413-48f3-8186-ff2e4a74d7b6"
Template: "583d498c-b413-48f3-8186-ff2e4a74d7b6"
Path: /sitecore/templates/Project/RainflyTraining/EventPage/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0a209e70-fbb1-4a7a-b468-56f47e2176dc"
      Hint: BrowserTitle
      Value: You should come to $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220801T124659Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c39dfbf8-ed2d-4dee-aa58-0ba8fbaadb90"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220801T124721Z
